### ISSUE TITLE
branch for slick 3.0?

### ISSUE THREAD

**Issue by hanfeisun** [typesafehub/activator-hello-slick#13]
I came from http://www.typesafe.com/activator/template/hello-slick-3.0

but found the project is not configured for slick 3.0....

**Comment by corruptmemory** [comment]
Agreed. @szeiger - should this be updated?

**Comment by Shookit** [comment]
Agree; this is out of date and being referred to by the Slick docs. Struggling with how to actually update to slick 3.0.

**Comment by cvogt** [comment]
did you check the slick-3.0 branch? https://github.com/typesafehub/activator-hello-slick/tree/slick-3.0

**Comment by Shookit** [comment]
I did not, but that's exactly what I was looking for. It might make sense to refer to this on the readme and/or slick documentation?

**Comment by szeiger** [comment]
It's a known bug on the typesafe.com website that github links for non-default branches are broken. The links in the manual are correct and take you to https://www.typesafe.com/activator/template/hello-slick-3.0 but the github link on that page does not encode the branch correctly. Everything else (e.g. downloading the template bundle from that page or opening the template directly in Activator) should give you the correct version.

**Comment by szeiger** [comment]
Here's the ticket for the web site: https://github.com/typesafehub/activator/issues/831
